version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - bodyclose
    - contextcheck
    - errname
    - errorlint
    - gocritic
    - misspell
    - nolintlint
    - revive
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
  settings:
    revive:
      rules:
        - name: exported
        - name: package-comments
        - name: var-naming
        - name: receiver-naming
        - name: indent-error-flow
        - name: error-strings
        - name: error-return
        - name: context-as-argument
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    presets:
      - std-error-handling
    paths:
      - examples/greeter/greeterpb

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/UsatovPavel/go-grpc-kit
